name: Test and Release

on:
  push:
    tags: v*.*.*

concurrency:
  group: ${{ github.workflow }}-${{ github.sha }}
  cancel-in-progress: true

jobs:
  release:
    name: Publish and release

    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Set up version
        run: |
          VERSION_REGEX="^[0-9]+\.[0-9]+\.[0-9]+$"
          if [[ "${GITHUB_REF#refs/tags/v}" =~ $VERSION_REGEX ]]; then
            echo "VERSION=${GITHUB_REF#refs/tags/v}" >> $GITHUB_ENV
          else
            echo "Error: Invalid version"
            exit 1
          fi

      - name: Update version in control file
        run: |
          sed -i "s/^Version: .*/Version: $VERSION/" debian/DEBIAN/control

      - name: Commit changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git diff --exit-code || git commit -am "Update version to $VERSION"

      - name: Package and publish
        run: |
          make package

      - name: Push changes
        uses: ad-m/github-push-action@master
        if: ${{ !startsWith(github.ref, 'refs/pull/') && success() }}
        with:
          github_token: ${{ github.token }}

      - name: Publish distributions
        uses: actions/upload-artifact@v4
        with:
          name: ${{ github.event.repository.name }}
          path: build/*.deb
          if-no-files-found: error

      - name: Release
        uses: EffectiveRange/version-release-github-action@v1
